### ISSUE TITLE
Plugin flow fail - As default

### ISSUE THREAD

**Issue by yehudah** [sc0ttkclark/ghost-meta#1]
Hi,

Trying to use the plugin, the plugin will not fail to continue because of the _get_meta_table function ?

**What I mean:**
update_ghost_meta --> update_metadata --> before trigger the "update_{$meta_type}_metadata" filter there is the _get_meta_table that will fail.

I'm missing something ?

**Comment by sc0ttkclark** [comment]
Sorry about that, fixed here using a hackaround. I plan on submitting a patch to WP core to make this more flexible by moving the `_get_meta_table` after the filter in the add/update/delete metadata functions.

https://github.com/sc0ttkclark/ghost-meta/commit/4728dff6dbd94b00e5a0f26cc43dc7fca605d194
